source 'https://rubygems.org'
ruby '2.3.1'
#
# Windows Support
#----------------------------------------------------
gem 'wdm' if Gem.win_platform?
#
# Slim
#----------------------------------------------------
gem 'slim', '>= 3.0'
#
# Middleman Gems
#----------------------------------------------------
gem 'middleman-sprockets',    '~> 4'
gem 'middleman-compass',      '~> 4'
gem 'middleman',              '~> 4'
gem 'middleman-autoprefixer', git: 'git@github.com:middleman/middleman-autoprefixer'
gem 'middleman-livereload',   git: 'git@github.com:middleman/middleman-livereload'
gem 'middleman-minify-html',  git: 'git@github.com:middleman/middleman-minify-html'
gem 'middleman-deploy',       git: 'git@github.com:middleman-contrib/middleman-deploy'
#
# Templating Engines
#----------------------------------------------------
gem 'coffee-script', '~> 2.4.1'
gem 'kramdown',      '~>1.13.2'
gem 'builder',       '~> 3.2.3'
gem 'sassc',         '~>1.11.2'
#
# Rails-Assets-Pipeline-Gems
#----------------------------------------------------
source 'https://rails-assets.org' do
  gem 'rails-assets-jquery'
  gem 'rails-assets-normalize.scss'
  gem 'rails-assets-sass-mediaqueries'
  gem 'rails-assets-font-awesome-sass'
end
