language: ruby
rvm:
  - ruby-head
  - 2.1.1
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-19mode
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
script: bundle exec cucumber
env: TEST=true
