language: ruby
sudo: false
cache: bundler
before_script:
- bundle update
rvm:
- ruby-head
- jruby-head
- 2.2
- 2.1
- 2.0
os:
- linux
matrix:
  fast_finish: true
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
env:
  global:
  - JRUBY_OPTS='-J-Xmx1024M'
  - TEST=true
script: bundle exec cucumber
notifications:
  slack:
    secure: O3D9z6MzH0jzc1BXA/Th2kaOYTYHTaqsSRhWVrrTtlo6EYi0RYQ4Qn42VJnK2uLPyOR+e5cRHeOkn95U18UPKsS1dODcrUXXLmS3pHdXJpUbo0qW3DYOyzVVc3H9zFohIyQWjO0cARButzFFFPe+8RO4t7VP1rqyWWXmf2TWU3M=
